name: Learning Python CI/CD

# Remove top-level permissions to inherit from caller
on:
  push:
    branches: [ main ]
    paths:
      - 'learningpython/**'
      - '.github/workflows/python-reusable.yml'
      - '.github/workflows/learningpython-workflow.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'learningpython/**'
      - '.github/workflows/python-reusable.yml'
      - '.github/workflows/learningpython-workflow.yml'
  workflow_dispatch:

jobs:
  call-reusable-workflow:
    permissions:
      contents: read
      issues: write
      packages: write
      pull-requests: write
    uses: ./.github/workflows/python-reusable.yml
    with:
      project_path: 'learningpython'
      python_version: '3.9'
      use_poetry: true
      use_docker: false
      needs_postgres: false
      coverage_threshold: 90
      artifact_name: 'learningpython-dist'
      artifact_path: 'dist'
