name: Python WebApp CI/CD

permissions:
  actions: write
  checks: write
  deployments: write
  pages: write
  security-events: write
  id-token: write
  contents: read
  packages: write
  issues: write
  pull-requests: write

on:
  push:
    branches: [ main ]
    paths:
      - 'webapp/**'
      - '.github/workflows/python-reusable.yml'
      - '.github/workflows/python-webapp-workflow.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'webapp/**'
      - '.github/workflows/python-reusable.yml'
      - '.github/workflows/python-webapp-workflow.yml'
  workflow_dispatch:

jobs:
  call-reusable-workflow:
    uses: gautampachnanda101/python-with-tests/.github/workflows/python-reusable.yml@08870d8af9e99eacdd75f62cfa6caa4845626c5e
    with:
      project_path: 'webapp'
      python_version: '3.9'
      use_poetry: true
      use_docker: false
      needs_postgres: false
      coverage_threshold: 90
      artifact_name: 'webapp-dist'
      artifact_path: 'dist'
