name: Format Code

on:
  workflow_dispatch:
    inputs:
      project:
        description: 'Project to format (learningpython or python-webapp)'
        required: true
        default: 'learningpython'
        type: choice
        options:
          - learningpython
          - python-webapp

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies for learningpython
      if: ${{ inputs.project == 'learningpython' }}
      working-directory: ./learningpython
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry config virtualenvs.create false
        poetry install

    - name: Install dependencies for python-webapp
      if: ${{ inputs.project == 'python-webapp' }}
      working-directory: ./python-webapp
      run: |
        python -m pip install --upgrade pip
        pip install black isort flake8

    - name: Format with Black
      working-directory: ./${{ inputs.project }}
      run: |
        if [ "${{ inputs.project }}" == "learningpython" ]; then
          poetry run black .
          poetry run isort .
        else
          black .
          isort .
        fi

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ github.token }}
        commit-message: "🤖 Auto-format code with Black and isort"
        title: "🤖 Auto-format ${{ inputs.project }} code"
        body: |
          This PR was automatically created by the Format Code workflow.

          It applies Black and isort formatting to the ${{ inputs.project }} codebase to ensure consistent code style.

          ## Changes
          - Applied Black formatting
          - Sorted imports with isort

          Please review the changes and merge if they look good!
        branch: auto-format-${{ inputs.project }}
        base: ${{ github.ref_name }}
        delete-branch: true
