name: Learning Python CI/CD

permissions:
  actions: write
  contents: read
  deployments: write
  issues: write
  packages: write
  pages: write
  pull-requests: write
  security-events: write
  id-token: write
  checks: write

on:
  push:
    branches: [ main ]
    paths:
      - 'learningpython/**'
      - '.github/workflows/python-reusable.yml'
      - '.github/workflows/learningpython-workflow.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'learningpython/**'
      - '.github/workflows/python-reusable.yml'
      - '.github/workflows/learningpython-workflow.yml'
  workflow_dispatch:

jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/python-reusable.yml
    with:
      project_path: 'learningpython'
      python_version: '3.9'
      use_poetry: false
      use_docker: false
      needs_postgres: false
      coverage_threshold: 80
      artifact_name: 'learningpython-artifacts'
      artifact_path: 'src'
