name: Python Web App CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'python-webapp/**'
      - '.github/workflows/python-reusable.yml'
      - '.github/workflows/python-webapp-workflow.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'python-webapp/**'
      - '.github/workflows/python-reusable.yml'
      - '.github/workflows/python-webapp-workflow.yml'
  workflow_dispatch:

jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/python-reusable.yml
    with:
      project_path: 'python-webapp'
      python_version: '3.9'
      use_poetry: false
      use_docker: true
      needs_postgres: true
      coverage_threshold: 80
      artifact_name: 'python-webapp-artifacts'
      artifact_path: 'app'

  deploy-staging:
    needs: call-reusable-workflow
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    environment: staging

    steps:
    - name: Deploy to staging
      run: |
        echo "Deploying to staging environment"
        # In a real scenario, you would add deployment steps here
        # For example, using SSH to connect to a staging server and pull the latest image
        echo "Deployed to staging at $(date)"

    - name: Verify deployment
      run: |
        echo "Verifying deployment to staging"
        # Add verification steps like health checks
        echo "Deployment verified at $(date)"

  deploy-production:
    needs: deploy-staging
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
    environment: production

    steps:
    - name: Deploy to production
      run: |
        echo "Deploying to production environment"
        # In a real scenario, you would add deployment steps here
        # For example, using SSH to connect to a production server and pull the latest image
        echo "Deployed to production at $(date)"

    - name: Verify deployment
      run: |
        echo "Verifying deployment to production"
        # Add verification steps like health checks
        echo "Deployment verified at $(date)"
